name:                blindpass
version:             0.0.0
github:              "jlamothe/blindpass"
license:             GPL-3
author:              "Jonathan Lamothe"
maintainer:          "jonathan@jlamothe.net"
copyright:           "Jonathan Lamothe"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Password entry tool
category:            Utilities

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jlamothe/blindpass#readme>

ghc-options:
- -Wall

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  blindpass:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - blindpass

tests:
  blindpass-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - blindpass
    - hspec >= 2.7.4 && < 2.8
